version: 2
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: linux
        goarch: 386
      - goos: windows
        goarch: 386
      - goos: windows
        goarch: arm64
archives:
  - id: presidium
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  - name: presidium-oapi3
    homepage: "https://github.com/spandigital/presidium"
    description: "Presidium is a software documentation management system for agile teams"
    repository:
      owner: spandigital
      name: homebrew-tap
    directory: Formula

npms:
  - name: "@spandigital/presidium-oapi3"
    description: "Presidium is a software documentation management system for agile teams"
    homepage: "https://github.com/spandigital/presidium"
    license: "MIT"
    author: "SPAN Digital <info@spandigital.com>"
    repository: "https://github.com/spandigital/presidium-oapi3"
    bugs: "https://github.com/spandigital/presidium-oapi3/issues"
    keywords:
      - presidium
      - documentation
      - openapi
      - swagger
      - markdown
      - cli
    access: public
    format: tar.gz
