jobs:
  include:
  - stage: Tag code
    if: branch IN (develop, master) AND type = push AND NOT (commit_message =~ /^.*\[NPM
      version\].*$/)
    language: go
    go:
    - 1.17.x
    services:
    - docker
    git:
      depth: false
    script:
    - "./build/ci/tag_code.sh"
  - stage: Release
    if: tag IS present
    language: go
    go:
    - 1.17.x
    script:
    - curl -sfL https://goreleaser.com/static/run | bash -s -- check
    deploy:
    - provider: script
      skip_cleanup: true
      script: curl -sfL https://goreleaser.com/static/run | bash
      on:
        tags: true
        condition: "${TRAVIS_TAG} =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+$"
    - provider: npm
      email: presidium@spandigital.com
      api_key:
        secure: YnHUaE/DF4nIrcUz6prrIMM4tbZRD3l0Gai3Rt6kufALxqhhuWwm3Y2Ub3Wu9xKvzdO0rSdtLABAVSnCfWi6bupy+YkE0uhdwOqsrSt9X+BVov/3XCNy7vHK0sif1XdSgfcud2y4EXnVchu7VsKl+ZZaNqQ36HRkpe8szWF5UujWEEHxiLrp6/WpY5lTp2NXfhbTAzmi74K0Eqg4Q0JhX5NvHAQUQVIjJszaugC8ZCQ30ODftW7/QgNxgtvXh3DdOwYs15yCfLInAkYpA3VJK/08pnGzCgWChoJ9J0pzhvYeIIUEFZIbBcsCsaVsxgwdC53EkFo3A7xTQJm2TQBrgYVN0uHngW+pXjQ56Am85YLS7qwzSmPTrwdUQFEwwW4yyirwstSV0B/Iw7QtyzXBF6ozR0tvJtiNXFN7zmhA5yRxcduEcmggClqt3KnaPuqk3F9Ne71OxE/ToqZW1k9JBEXKkwjXT/kVxhrR6SBiTf01Ze3gdDjqHifA16NAd/0pP32xA2Db1TPiBqxnqLRKTMVXpvJ8Rgg4Sj/CGeEFqM0kuCFO7AbBSTmqAVWSuMlOdtfbOG2vACD6sBoO33sF+kpM8yoIH9IvcMQUfzndqKR6iUOtjIXrZB/KKPNsDvNoDJHO8/3mTdmTKRdq/nX4B4fibUr+cHeqvdbhx9J8PvI=
      on:
        tags: true
        repo: SPANDigital/presidium-oapi3
        condition: "${TRAVIS_TAG} =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+$"
    after_deploy:
    - "./build/ci/tags_cleanup.sh"
env:
  global:
  - secure: md2ipjVOZOF/bE8MiwiRtk1+t6MmLNN9BQri7bOERPsZb3QnCdHhkhvy2JSTEnZgUoa1xtwe35bsYMkpLMKxfNX9sdksi63CXPptszDSPhBQRX0iw7URV1SKJiNLbcWl1XaMSdZShDS1nri5V8TMU6gCqtIbN+5kktKUu28WTgyB0mNKKKoOHsHARCvzbGrqmDgrQSqVZQW3XUfxky0+yd0FCN5FLs2xRhSRpo671ZlvfZLofPlbusnnvqNldlujy8i7x7UMSTUfdzLpY10/Z6dv+BKE0zD08ggKNCkE+9yI7XJ4sdEe6/w5Frk9xirRGjcBD7BBEjwLNyEzO+0gXTWIgvTQPD3eR4FZzf3DQLCizfwhjKtNgX6crdOaE05iYqUNhMFhpOt4qN71Y/fxW7jpypSpEK8kwO13NwUhByyMJS6ch7AZwX94re7ZvRxOS/CaeKnW1by9e38zlbBIU0OBn9zzysQQGxf0hCafHDHWTVb59hQ6/mYTWOrl7RxmhKevIo/3qy9rL/TdSKiKuadxN+xlCNKHjIrj18UXyZFpra1RGjOdanW2amDFHxm2FTAQlr7Mhx6Gr4o7nDQMU6IqhAh4wHc1wH/SysW65KBqzqVvrIrbxxWn9g0N7SmiFjnKKKoIHzdrv4sO1QVSvlLat4/nWi0K0e0KcPKpXbQ=
