os: linux
dist: focal
language: go
cache:
  directories:
  - "$HOME/gopath/pkg/mod"
jobs:
  include:
  # - stage: tests
  #   name: Run Tests
  #   if: env(TEST) IS NOT present AND type = push AND tag IS NOT present
  #   language: go
  #   go:
  #   - 1.20.x
  #   git:
  #     depth: false
  #   script:
  #   - make test || travis_terminate 1
  - stage: Tag code
    if: branch IN (develop, main) AND type = push AND NOT (commit_message =~ /^.*\[NPM
      version\].*$/)
    language: go
    go:
    - 1.20.x
    services:
    - docker
    git:
      depth: false
    script:
    - "./build/ci/tag_code.sh"
  - stage: Release
    if: tag IS present
    language: go
    go:
    - 1.20.x
    script:
    - curl -sfL https://git.io/goreleaser | sh -s -- check
    deploy:
    - provider: script
      skip_cleanup: true
      script: curl -sL https://git.io/goreleaser | bash
      on:
        tags: true
        condition: "${TRAVIS_TAG} =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+$"
  #  - provider: npm
  #    email: presidium@spandigital.com
  #    api_key:
  #      secure: YnHUaE/DF4nIrcUz6prrIMM4tbZRD3l0Gai3Rt6kufALxqhhuWwm3Y2Ub3Wu9xKvzdO0rSdtLABAVSnCfWi6bupy+YkE0uhdwOqsrSt9X+BVov/3XCNy7vHK0sif1XdSgfcud2y4EXnVchu7VsKl+ZZaNqQ36HRkpe8szWF5UujWEEHxiLrp6/WpY5lTp2NXfhbTAzmi74K0Eqg4Q0JhX5NvHAQUQVIjJszaugC8ZCQ30ODftW7/QgNxgtvXh3DdOwYs15yCfLInAkYpA3VJK/08pnGzCgWChoJ9J0pzhvYeIIUEFZIbBcsCsaVsxgwdC53EkFo3A7xTQJm2TQBrgYVN0uHngW+pXjQ56Am85YLS7qwzSmPTrwdUQFEwwW4yyirwstSV0B/Iw7QtyzXBF6ozR0tvJtiNXFN7zmhA5yRxcduEcmggClqt3KnaPuqk3F9Ne71OxE/ToqZW1k9JBEXKkwjXT/kVxhrR6SBiTf01Ze3gdDjqHifA16NAd/0pP32xA2Db1TPiBqxnqLRKTMVXpvJ8Rgg4Sj/CGeEFqM0kuCFO7AbBSTmqAVWSuMlOdtfbOG2vACD6sBoO33sF+kpM8yoIH9IvcMQUfzndqKR6iUOtjIXrZB/KKPNsDvNoDJHO8/3mTdmTKRdq/nX4B4fibUr+cHeqvdbhx9J8PvI=
  #    on:
  #      tags: true
  #      repo: SPANDigital/presidium-oapi3
  #      condition: "${TRAVIS_TAG} =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+$"
    after_deploy:
    - "./build/ci/tags_cleanup.sh"
env:
  global:
  - secure: f6yCpw7i53fgcDO3vKRn5wTvU1v9zXkaFgCAKNOIlA5GhZG5eQuQuyFecNlh499XYxOofgYhozI4XMll3j9PitM+d+dapd9HSyu0b2BsDxt8+SqW5eQtKg7xXHPpx8NCvliz0Xtx2wM+kuaE3w4NKQLEL9q/r50TpVX+dT1Jyx8FaWMCTn9Kh/kIdsFfjXBTq11PZXSU33lWHwE81bUguBvLxQv3ck2E3RA9E6GDdsmYkr35cxoWgxR9kA0qHb5QwbT1nW0jk+umUmcMvviq+XObj8/2YaiuNmhQu6Wbmmdm+/s8md3sA+dV/HKljmD4vKetRGgHs3aeqkDvchlv5bHhTEAYv5iLMc2slWmgZAmTBLFC6NtpC1KxQdQp2pc6+fylaGhh4KUkMcdoOOhatYc1pYs59tE3/UUOvK5tBy/qee2eZjBDJsxePVrRZTcXV4yGR57fUzWwqZsnwcfEW0G9OvW/Z6Xwo88mY9TEjpRwRKoEfScEChWyLcp8LdyKgCovt7+nTpdufBwh0+XjP9BL0BnqabyfCZ0r/QS5SLHrw376IT/KIvilaELWu93bmoNmLau4G1GqbmAqkVxGNFntNBOg0+uQ8xxcW5AsQX4wL0WZ5fG6NX7UT46hsXZkQOMCWEgVy+3AxThIq1KbdL6P/ZjZyvGvp//K0rEmnWY=
  - TMPDIR=/tmp/
  - CACHE_DIR=$HOME/.cache
  - CACHE_FILE_GO=$CACHE_DIR/go-alpine.tar.gz
  - GO111MODULE=on
